<?php

/**
 * Define all constants
 */
const ROLE_ADMIN = 1;
const ROLE_DRIVER = 2;
const ROLE_CUSTOMER = 3;
const USER_STATUS_INACTIVE = 1;
const USER_STATUS_ACTIVE = 2;

const ORDER_STATUS_PENDING = 1;
const ORDER_STATUS_CONFIRMED = 2;
const ORDER_STATUS_OUT_FOR_PICKUP = 3;
const ORDER_STATUS_PICKED_UP = 4;
const ORDER_STATUS_IN_TRANSIT = 5;
const ORDER_STATUS_OUT_FOR_DELIVERY = 6;
const ORDER_STATUS_DELIVERED = 7;
const ORDER_STATUS_RETURNED = 8;
const ORDER_STATUS_COMPLETED = 9;
const ORDER_STATUS_CANCELLED = 10;

const PAYMENT_STATUS_SUCCESS = 1;
const PAYMENT_STATUS_FAILED = 2;
const PAYMENT_STATUS_PENDING = 3;
const PAYMENT_STATUS_CANCELLED = 4;
const VEHICLE_STATUS_IN_SERVICE = 1;
const VEHICLE_STATUS_OUT_OF_SERVICE = 2;
const PAYMENT_CREDIT_CARD = 2;
